### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by designermonkey** [ArcanjoQueiroz/wait-for#4]
It may be me, but is there a better usage example for how we would proceed _after_ wait-for completed?

I use docker-compose and have no idea what to do, i.e. how to run another command in a container after this is finished.

Would you be able to provide at least another example on how this works in practice?

Thanks.

**Comment by ArcanjoQueiroz** [comment]
You can use wait-for command inside the command property of a service in your docker-compose.yml. 
In the following example, you can see two services: the first one is a **PostgreSQL** (postgres) and the second one
a **Flyway** container (schema). The Flyway waits for PostgreSQL to be available and then run the migration command:

```yml
version: '3'
services:
  postgres:
    image: postgres:11-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  schema:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flyway-postgres
    command: >
      bash -c "wait-for --type postgres \
        --host postgres \
        --port 5432 \
        --user test \
        --password test \
        --name test \
        --seconds 2 \
        --maxAttempts 20 && \
        flyway \
          -url=jdbc:postgresql://postgres:5432/test \
          -schemas=test \
          -user=test \
          -password=test migrate" # Here
    volumes:
      - ./migrations:/flyway/sql
      - ./drivers:/flyway/drivers
    depends_on:
      - postgres
```

And inside the schema Dockerfile we add wait-for v0.0.3 to do that:

```
ENV WAIT_FOR_VERSION=v0.0.3

# Adding wait-for
RUN wget "https://github.com/ArcanjoQueiroz/wait-for/releases/download/${WAIT_FOR_VERSION}/wait-for" \
  && chmod u+x wait-for && mv wait-for /usr/local/bin/wait-for \
  && echo -ne "- with Flyway $FLYWAY_VERSION\n" >> /root/.built
```

Wait-for follows the Unix programming convention, so you can use as you wish.

I am going to add some examples inside examples directory.
